### ISSUE TITLE
Internal Server Error when looking up someone to tag them.

### ISSUE THREAD

**Issue by kb0304** [WideChat/Rocket.Chat#297]

**Comment by shubhsherl** [comment]
@ear-dev Can you please provide the logs from the server. Thanks.

**Comment by shubhsherl** [comment]
@ear-dev this error is still not solved. Can you please provide the logs of Internal Server Error from the server, when you try to tag someone in the room.

**Comment by ear-dev** [comment]
@shubhsherl this is the error we are seeing in the logs......  seems like the same query error as the other one?

server.js:204 Meteor ➔ method spotlight -> userId: rTQJN7BthzWFDp6iE, arguments: ["jay",{},{"users":true},"uPWzqAKcPGvjhw3mZ"]
Exception while invoking method 'spotlight' MongoError: error processing query: ns=rocketchat.users limit=5Tree: $and
    $or
        settings.preferences.discoverability $eq "all"
        $not
            settings.preferences exists
    $or
        email regex /jay/i
        TEXT : query=jay, language=none, caseSensitive=0, diacriticSensitive=0, tag=NULL
    active $eq true
    username exists
    $not
        username $in [ ]
Sort: { username: 1 }
Proj: { username: 1, name: 1, status: 1, statusText: 1 }
 No query solutions
    at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:443:61)
    at Connection.emit (events.js:311:20)
    at Connection.EventEmitter.emit (domain.js:482:12)
    at processMessage (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:364:10)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:533:15)
    at Socket.emit (events.js:311:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
 => awaited here:
    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at packages/mongo/mongo_driver.js:1037:14
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1086:38)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1100:22)
    at SynchronousCursor.map (packages/mongo/mongo_driver.js:1110:10)
    at SynchronousCursor.fetch (packages/mongo/mongo_driver.js:1134:17)
    at Cursor.<computed> [as fetch] (packages/mongo/mongo_driver.js:882:44)
    at MethodInvocation.spotlight (server/publications/spotlight.js:76:80)
    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43

**Comment by shubhsherl** [comment]
@ear-dev 
![image](https://user-images.githubusercontent.com/34231951/84748423-41cc6d80-afd6-11ea-8f76-754f844e985b.png)
^Showing members from `bienvenido` channel.
There are some users with empty username in the deployment. Can you check that, and delete those users.

**Comment by ear-dev** [comment]
@shubhsherl I actually deleted those public channels.

**Comment by shubhsherl** [comment]
@ear-dev can you confirm if there is no user with an empty username in the deployment. And also if the log is same as above when you query user from [directory](https://dev.veranda.viasat.io/directory/users).
The problem occurs only when I query user, for channels the search the working fine(confirmed from directory page).

**Comment by ear-dev** [comment]
@shubhsherl there do seem to be several users with no username.  Do you know how that can happen?  At one point Jay had enabled Admin approval for new users, and it actually seems like those are the users without usernames. If this is the issue then we may want to fix that bug.  Thanks!

**Comment by ear-dev** [comment]
@shubhsherl I just gave usernames to any user who did not have one, but am still seeing the issue.  could be that we're in a bad state that needs cleaning up somehow?

**Comment by shubhsherl** [comment]
Thanks @ear-dev I'll look into this issue further. I thought those usernames are creating a problem, but the problem is something else. 🤔

**Comment by ear-dev** [comment]
Hi @shubhsherl I know you are busy with a bunch of stuff right now.....  but the next time you get free, I'd like to see if we can resolve this error.  "No query solutions"....  we need eventually to figure this out since those error messages reflect very badly on our app.  Thanks!

**Comment by shubhsherl** [comment]
@ear-dev Sure .
Can you confirm one more thing, if the log is same as above when you query user from [directory](https://dev.veranda.viasat.io/directory/users). It should be same, just want to confirm.

**Comment by ear-dev** [comment]
@shubhsherl yes, it's also a 'No query solutions' error. 

```irection":"asc","offset":0,"limit":25}]
server.js:204 API ➔ debug get directory threw an error: MongoError: error processing query: ns=rocketchat.usersTree: $and
    $or
        federation.origin $eq ""
        $not
            federation exists
    $or
        settings.preferences.discoverability $eq "all"
        $not
            settings.preferences exists
    $or
        email regex /karan/i
        TEXT : query=karan, language=none, caseSensitive=0, diacriticSensitive=0, tag=NULL
    active $eq true
    username exists
    $not
        username $in [ ]
Sort: {}
Proj: {}
 No query solutions
    at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:443:61)
    at Connection.emit (events.js:311:20)
    at Connection.EventEmitter.emit (domain.js:482:12)
    at processMessage (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:364:10)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:533:15)
    at Socket.emit (events.js:311:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
 => awaited here:
    at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at DDPCommon.MethodInvocation.<anonymous> (app/api/server/v1/misc.js:193:61)
    at packages/dispatch_run-as-user.js:211:14
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)
    at Object.get (app/api/server/v1/misc.js:193:25)
    at app/api/server/api.js:368:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:368:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9
server.js:204 API ➔ debug Failure {
  statusCode: 400,
  body: {
    success: false,
    error: 'error processing query: ns=rocketchat.usersTree: $and\n' +
      '    $or\n' +
      '        federation.origin $eq ""\n' +
      '        $not\n' +
      '            federation exists\n' +
      '    $or\n' +
      '        settings.preferences.discoverability $eq "all"\n' +
      '        $not\n' +
      '            settings.preferences exists\n' +
      '    $or\n' +
      '        email regex /karan/i\n' +
      '        TEXT : query=karan, language=none, caseSensitive=0, diacriticSensitive=0, tag=NULL\n' +
      '    active $eq true\n' +
      '    username exists\n' +
      '    $not\n' +
      '        username $in [ ]\n' +
      'Sort: {}\n' +
      'Proj: {}\n' +
      ' No query solutions',
    stack: undefined
  }
}
```

**Comment by shubhsherl** [comment]
@ear-dev the error is gone after catchup, I am not seeing any 'Internal Server Error'.
